### PR TITLE
Fix binding ordering script

### LINKED ISSUE #178: The sorting script doesn't work
## Bug description

When I was working on the C# major mode, and try to sort with the script. It doesn't even work..

## To Reproduce

1. Run `npm run sort-bindings`

## Expected behavior

Out of place key bindings should be sorted

### PR DESCRIPTION
**Pull request by stevenguh**
Fix #178

As I was writing C# major mode, I realized the sorting script was broken, so I rewrote it base on my observation on how keys are ordered in spacemacs.

1. order non-bindings type first
2. order by single character key -> non single key -> key with modifier like C-v
3. order key
    - shifting the A-Z to the end of ASCII set (This is evident when you look at the `{` keys in `SPC w` or `~` keys in `SPC T`)
    - swap space and tab so space is in the front

I also removed the special case for major mode to order it to the bottom because in spacemacs, `m` only shows up when it's applicable. But in our case the `m` entry show up regardless, so I just order it like that rest of the bindings.

### CODE REVIEW

File: scripts/sort.js [hunk 1]
```diff
@@ -29,56 +26,85 @@ function getType(b) {
...
+function compareFunction(a, b) {
+    let diff = getTypeOrder(getType(a)) - getTypeOrder(getType(b));
+    if (diff !== 0) { return diff; }
+
+    diff = getKeyTypeOrder(a) - getKeyTypeOrder(b);
+    if (diff !== 0) { return diff; }
+
+    diff = getKeyTypeOrder(a) - getKeyTypeOrder(b);
+    if (diff !== 0) { return diff; }
+
```
Comment (MarcoIeni) [inline scripts/sort.js:107]:
```suggestion
```
is it normal that this part is repeated?

Comment (stevenguh) [reply scripts/sort.js]: Good catch! remove!
